name: Fetch WBGT Data using Proxy

on:
  schedule:
    # 3時間ごとに実行（0時、3時、6時...）
    - cron: '0 0/3 * * *'
  # 手動実行も可能に
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Fetch WBGT data using proxy
        env:
          SCRAPING_BEE_API_KEY: ${{ secrets.SCRAPING_BEE_API_KEY }}
        run: node scripts/fetch-wbgt-proxy.js
      
      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/
          git commit -m "Update WBGT data $(date +"%Y-%m-%d %H:%M")" || exit 0
          git push
